version: "3.9"

services:
  app:
    build: .
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
